### PR TITLE
fixed IngameTick value

### PR DESCRIPTION
**Pull request by akiver**
The IngameTick field didn't reflect to the tick reported by the demo file, now it is.

### CODE REVIEW

**Comment by moritzuehling** [comment]
This would most likely break

* [ParsingProgress](https://github.com/akiver/demoinfo/blob/5e19127946676c174f6567559bab23f763f6c07b/DemoInfo/DemoParser.cs#L445) and
* [CurrentTime](https://github.com/akiver/demoinfo/blob/5e19127946676c174f6567559bab23f763f6c07b/DemoInfo/DemoParser.cs#L465)

Have you tested this?

**Comment by akiver** [comment]
I just tested it, these 2 values was wrong.
I pushed a fix but the tick value from NETTick is not used now (it returns strange value).

**Comment by moritzuehling** [comment]
This reversed the last commit, so I don't think it's useful. Ingame-Tick is the way to go then. I think renaming CurrentTick would do the trick. I'll look into a better solution, but I can't promise anything.

**Comment by akiver** [comment]
mmmm the last commit revert partially the 1st commit.
The important thing in the last commit is that IngameTick (https://github.com/akiver/demoinfo/blob/e08732e2bc8af03c95a060677902cd613dad086a/DemoInfo/DemoParser.cs#L579) correspond to the tick displayed by the demo (it is not the case ATM).
ParsingProgress and CurrentTime are working as before.
Thanks

**Comment by moritzuehling** [comment]
I can't reopen the pull-request - that would be something you need to do.

**Comment by akiver** [comment]
I made clean PR.
Thanks

**Pull request closed without merging**
