### PR TITLE
implented UserMessage parser

### PR DESCRIPTION
**Pull request by akiver**
There are few usefuls messages except CCSUsrMsg_SayText2 / CCSUsrMsg_SayText and maybe
CCSUsrMsg_ServerRankUpdate (rank is provided as int and only when the
player rank up). Maybe more?

I added it to get match's chat to extract it but mostly to be able to analyze properly eBot demos as it indicates the state of the match.
I removed the SLOW_PROTOBUF flag and added a bool DemoParser.ParseUserMessages (false by default) that needs to be to true to parse UserMessage.

I understand that you may consider it as a no necessary addition.

Thanks

### CODE REVIEW

**Comment by akiver** [comment]
My bad CCSUsrMsg_ServerRankUpdate is triggered at the end of each MM match only.

**Comment by akiver** [comment]
CCSUsrMsg_ServerRankUpdate has a field (int)rank_id which give the player's rank, it can be useful.

**Comment by main--** [comment]
As you probably noticed, SLOW_PROTOBUF is very convenient for development: You can simply deserialize protobuf messages and look at them. However, this significantly slows down the parser which is why it's disabled by default.

The idea behind this architecture is simple: protobuf-net isn't fast enough for our purposes, so we first use SLOW_PROTOBUF to find the message type we need and then use our custom optimized protobuf backend to implement the message by hand.

This last step is missing in your pull request: You did the hard part and found the message you need, but now there's no need to take the performance hit - just implement a [FastNetmessage](https://github.com/EHVAG/demoinfo/tree/master/DemoInfo/DP/FastNetmessages).

Just ask if anything is unclear.

**Comment by akiver** [comment]
I made an other PR with SLOW_PROTOBUF ATM.
Thanks

**Pull request closed without merging**
