### PR TITLE
fix inverted surrender team in RoundEndReason

### PR DESCRIPTION
**Pull request by akiver**

### CODE REVIEW

**Comment by moritzuehling** [comment]
Hm, do you have a Source for this? How many demos did you test it with?

**Comment by akiver** [comment]
I tested on 2 demos but only with T as surrenderer.
I'm thinking now that maybe there is a new reason?

**Comment by moritzuehling** [comment]
Hm, might be. I'm merging it as I have no counter-example. 

Maybe it is because both teams surrendered in the 2nd half and it refers to the starting side? Could be something stupid like that.

**Comment by akiver** [comment]
The surrender occurs on demos I tested at ~ 10 rounds (1st side).

**Pull request merged**
